name: airspothealth
description: "App for Airspot Health"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  flutter_riverpod: ^2.5.1
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.33.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/airspot.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
